name: Bandit Code Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install bandit
      - run: bandit -r . -f sarif -o bandit.sarif || true
      - name: Upload Bandit report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif
